image: python:3.13

stages:
  - lint
  - type_check
  - test

before_script:
  - pip install -r requirements.txt
  - pip install pytest ruff 

lint:
  stage: lint
  script:
    - ruff check .
    - ruff format --check .

test:
  stage: test
  script:
    - python -m pytest

security:
  stage: test
  script:
    - bandit -r app
    
type_check:
  stage: type_check
  script:
    - mypy .

