image: python:3.13

stages:
  - lint
  - test

before_script:
  - pip install -r requirements.txt
  - pip install pytest ruff

lint:
  stage: lint
  script:
    - ruff check .
    - ruff format --check .

test:
  stage: test
  script:
    - python -m pytest